# =========================================================================
# KUBERNETES INTERNAL SERVICE DISCOVERY
# =========================================================================

userservice:
  base-uri: http://obtb-user-service:8082

authservice:
  base-uri: http://obtb-auth-service:8081

configserver:
  base-uri: http://obtb-config-server:8083

notificationservice:
  base-uri: http://obtb-notification-service:8084

transactionservice:
  base-uri: http://obtb-transaction-service:8085

busService:
  base-uri: http://obtb-bus-service:8086

bookingService:
  base-uri: http://obtb-booking-service:8087

# Angular runs outside the cluster
angular:
  base-uri: http://localhost:4200

spring:
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            provider: my-auth-server
            client-id: obtb-api-gateway
            client-secret: obtb-api-gateway-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/api-gateway"
            scope: openid, profile
            client-authentication-method: client_secret_basic

        provider:
          my-auth-server:
            issuer-uri: ${oauth.issuer-uri}
            authorization-uri: ${authservice.base-uri}/oauth2/authorize
            token-uri: ${authservice.base-uri}/oauth2/token
            jwk-set-uri: ${authservice.base-uri}/oauth2/jwks

      resourceserver:
        jwt:
          issuer-uri: ${oauth.issuer-uri}
          jwk-set-uri: ${authservice.base-uri}/oauth2/jwks
