# =========================================================================
# API GATEWAY CONFIGURATION FOR DEV PROFILE
# =========================================================================

userservice:
  base-uri: http://localhost:8082

authservice:
  base-uri: http://localhost:8081

configserver:
  base-uri: http://localhost:8083

notificationservice:
  base-uri: http://localhost:8084

transactionservice:
  base-uri: http://localhost:8085

busService:
  base-uri: http://localhost:8086

bookingService:
  base-uri: http://localhost:8087

# Angular runs outside the cluster
angular:
  base-uri: http://localhost:4200


spring:
  security:
    oauth2:
      client:
        registration:
          api-gateway:
            provider: my-auth-server
            client-id: obtb-api-gateway
            client-secret: obtb-api-gateway-secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/api-gateway"
            scope: openid, profile
            client-authentication-method: client_secret_basic

        provider:
          my-auth-server:
            issuer-uri: "${oauth.issuer-uri:http://localhost:8081}"
            authorization-uri: "${authservice.base-uri:http://localhost:8081}/oauth2/authorize"
            token-uri: "${authservice.base-uri:http://localhost:8081}/oauth2/token"
            jwk-set-uri: "${authservice.base-uri:http://localhost:8081}/oauth2/jwks"

      resourceserver:
        jwt:
          issuer-uri: "${oauth.issuer-uri:http://localhost:8081}"
          jwk-set-uri: "${authservice.base-uri:http://localhost:8081}/oauth2/jwks"

gateway:
  routes:
    auth-prefix: /auth
    user-prefix: /user
    bus-prefix: /bus
    booking-prefix: /booking
    txn-prefix: /txn
