# =========================================================================
# KUBERNETES INTERNAL SERVICE DISCOVERY
# =========================================================================

userservice.base-uri=http://obtb-user-service:8082
public-auth-service.base-uri=https://disgrace-shampoo-detonator.ngrok-free.dev/auth

authservice.base-uri=http://obtb-auth-service:8081

configserver.base-uri=http://obtb-config-server:8083

notificationservice.base-uri=http://obtb-notification-service:8084

transactionservice.base-uri=http://obtb-transaction-service:8085

busService.base-uri=http://obtb-bus-service:8086

bookingService.base-uri=http://obtb-booking-service:8087

# Angular runs outside the cluster
angular.base-uri=https://disgrace-shampoo-detonator.ngrok-free.dev

# Leave unchanged for now
oauth.issuer-uri=https://disgrace-shampoo-detonator.ngrok-free.dev/auth

# Logging
logging.level.org.springframework.web=DEBUG
