spring.spring.application.name=BookingService
server.port=8087

spring.datasource.url=jdbc:postgresql://localhost:5433/OBTB_BOOKINGDB?sslmode=prefer
spring.datasource.username=postgres
spring.datasource.password=Mimioscar@030203
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


oauth2.client.registration-key=client
spring.security.oauth2.client.registration.client.provider=OauthService
spring.security.oauth2.client.registration.client.client-id=obtb-client-007
spring.security.oauth2.client.registration.client.client-name=obtb-BookingService-client-007
spring.security.oauth2.client.registration.client.client-secret=obtb-BookingService-client-007
spring.security.oauth2.client.registration.client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.client.scope[0]=openid
spring.security.oauth2.client.registration.client.scope[1]=profile
spring.security.oauth2.client.registration.client.scope[2]=internal
spring.security.oauth2.client.provider.OauthService.issuer-uri=http://localhost:8081
spring.security.oauth2.client.provider.OauthService.token-uri=http://localhost:8081/oauth2/token



cloudinary.cloudName=dapbqi4tj
cloudinary.apiKey=863264178627592
cloudinary.apiSecret=DxkG6_hpyMdYEm8yFHwOkw-XJf8
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false

# CONSUMER FIXES
spring.kafka.consumer.group-id=booking-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.value.default.type=org.hexaware.bookingservice.dtos.eventDtos


kafka.topics[0].topic=booking-initiated-topic
kafka.topics[0].partitions=3
kafka.topics[0].replication=1

kafka.topics[1].topic=payment-events-topic
kafka.topics[1].partitions=3
kafka.topics[1].replication=1
kafka.topics[1].replication=1

