spring.application.name=UserService
server.port=8082

# =========================================================================
# KUBERNETES POSTGRESQL CONFIGURATION
# =========================================================================
spring.datasource.url=jdbc:postgresql://postgres:5432/user_service_db
spring.datasource.username=admin
spring.datasource.password=Mimioscar@030203
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# =========================================================================
# RESOURCE SERVER JWT VALIDATION
# =========================================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${oauth.issuer-uri:http://localhost:8081}

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${authservice.base-uri:http://obtb-auth-service:8081}/oauth2/jwks

# =========================================================================
# OAUTH2 CLIENT REGISTRATION (Inter-service authentication)
# =========================================================================
oauth2.client.registration-key=client

spring.security.oauth2.client.registration.client.provider=OauthService
spring.security.oauth2.client.registration.client.client-id=obtb-client-004
spring.security.oauth2.client.registration.client.client-name=obtb-userservice-client-004
spring.security.oauth2.client.registration.client.client-secret=obtb-userservice-client-004
spring.security.oauth2.client.registration.client.authorization-grant-type=client_credentials

spring.security.oauth2.client.registration.client.scope[0]=openid
spring.security.oauth2.client.registration.client.scope[1]=profile

spring.security.oauth2.client.provider.OauthService.issuer-uri=${oauth.issuer-uri:http://localhost:8081}

spring.security.oauth2.client.provider.OauthService.token-uri=${authservice.base-uri:http://obtb-auth-service:8081}/oauth2/token

# =========================================================================
# KUBERNETES KAFKA CONFIGURATION
# =========================================================================
spring.kafka.bootstrap-servers=kafka-broker:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

spring.kafka.consumer.group-id=wallet-group
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer

spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer

spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false

spring.kafka.consumer.properties.spring.json.value.default.type=org.hexaware.userservice.dtos.eventDtos.SagaEvent

# Kafka Orchestration Topics
kafka.topics[0].topic=booking-initiated-topic
kafka.topics[0].partitions=3
kafka.topics[0].replication=1

kafka.topics[1].topic=payment-events-topic
kafka.topics[1].partitions=3
kafka.topics[1].replication=1

# =========================================================================
# EXTERNAL CLOUDINARY FILE STORAGE
# =========================================================================
cloudinary.cloudName=dapbqi4tj
cloudinary.apiKey=863264178627592
cloudinary.apiSecret=DxkG6_hpyMdYEm8yFHwOkw-XJf8
